### PR TITLE
Add attribyte OID usually added to Java keystores

### PR DESCRIPTION
**Pull request by lulf**
This allows PKCS12 stores encoded by go-pkcs12 to be read as Java
keystores in JDK >= 8

See https://github.com/kaikramer/keystore-explorer/issues/35#issuecomment-223837809 for more information.

### CODE REVIEW

**Comment by AGWA** [comment]
According to the linked explanation, this attribute is only necessary when producing trust stores. Are you trying to produce a trust store?

**Comment by lulf** [comment]
@AGWA Yes, I am. I see that keytool adds this attribute for CAs imported to a keystore. From what I can tell, a trust store is just a keystore with certs that you want to trust.

**Comment by AGWA** [comment]
OK. The current API doesn't make sense for encoding a trust store because it requires a private key and leaf certificate, which aren't applicable to a trust store.  We would need a new function that looks like:

```golang
func EncodeTrustStore(rand io.Reader, certs []*x509.Certificate, password string) (pfxData []byte, err error)
```

Can you point to any documentation for the `2.16.840.1.113894.746875.1.1` OID?  How did you come up with the value of the attribute?

**Comment by lulf** [comment]
@AGWA Agreed that it makes sense to have an additional API for encoding 'pure' trust stores.

In my case, however, I am using a combined keystore and truststore, as I am using it for internal mutual TLS certificates, storing both the CA to trust and the private key + cert for each trusted component. So having them in the same store is a lot more convenient as I only need to distribute 1 rather than 2 files to each component.

Regarding the value, I have that from the github issue I linked to, and I verified the behavior by creating a Java keystore using keytool, and inspecting the attributes using this library and openssl print which displays this attribute value. I also just now looked it up in the OpenJDK source code: 

https://github.com/openjdk/jdk/blob/4e430ffbb6de8a578fc6ece00f44ef2100af109f/src/java.base/share/classes/sun/security/pkcs12/PKCS12KeyStore.java#L181

**Comment by AGWA** [comment]
Thanks for explaining your use case.  I understand the convenience of using a single file for both a key and trust store, but allowing a key store to be used as a trust store makes it way too easy to create a serious misconfiguration.  I've seen production systems accidentally use a server certificate chain containing a public CA as a trusted CA store for client authentication, and in doing so unwittingly allow anyone to connect to the service.  Requiring a special attribute for trust store certs is a very smart safety feature in Java, and including the attribute on certs produced by `Encode` would be bypassing that safety feature, which I am not willing to do.

**Comment by lulf** [comment]
@AGWA Understandable. I've raised #10 then based on your proposal. I also took the liberty of adding a DecodeTrustStore.

**Pull request closed without merging**
