### PR TITLE
Support of password-less private key bag is added

### PR DESCRIPTION
**Pull request by yastrebtsov**

### CODE REVIEW

**Comment by AGWA** [comment]
Support for this is already present on the encoder branch (771e73b7890a517f89de6ff3919545c64d679171) and will be included in the next version of go-pkcs12.

**Comment by yastrebtsov** [comment]
Thank you for the response. I've taken note of that. A minor suggestion: Could we consider adding support for the oidPublicKeyRSA algorithm (x509.ParsePKCS1PrivateKey function)? 
Many tools commonly use this algorithm during PFX generation, so it might be beneficial to support it.

**Comment by AGWA** [comment]
Could you clarify what you mean? Is there a bag type which contains a PKCS#1 private key rather than a PKCS#8 key?  I don't see such a bag type defined in https://datatracker.ietf.org/doc/html/rfc7292#section-4.2 so if you could provide a reference to some specification or upload an example PKCS#12 file it would be helpful.

**Comment by yastrebtsov** [comment]
> Could you clarify what you mean? Is there a bag type which contains a PKCS#1 private key rather than a PKCS#8 key?

Yes, Algorithm with OID {1, 2, 840, 113549, 1, 1, 1} is supported too. Sample pfx file is attached. (generated by openssl)
[no_encryption.pfx.zip](https://github.com/SSLMate/go-pkcs12/files/12731430/no_encryption.pfx.zip)

**Comment by AGWA** [comment]
That file is already supported by the `encoder` branch.

**Pull request closed without merging**
