### PR TITLE
Support triple DES certificate encryption

### PR DESCRIPTION
**Pull request by Marc-Pons**
Add support to encrypt P12 certificates with triple DES. Pretty much equivalent to "-descert" flag of openssl.

I require this functionality because openssl 3 throws an error when trying to parse P12 that use RC2 algorithm when "-legacy" flag is not specified.

### CODE REVIEW

**Comment by Marc-Pons** [comment]
Hi @AGWA, is there any chance this PR could be reviewed? Thank you!

**Comment by AGWA** [comment]
I would rather not add support for a legacy algorithm. If the concern is OpenSSL 3 compatibility as indicated in #36, then presumably AES-256 support would address your use case?

**Comment by Marc-Pons** [comment]
Hi AGWA, thanks for taking your time replying. Actually I picked 3DES cause it was already supported in the library, just wanted to offer the possibility to encrypt P12's certs with it instead of RC2. However, I'm afraid that AES is not fully supported on old devices as is 3DES.

**Comment by pschou** [comment]
I'd recommend a different method, see #39 as passing in a config struct would allow options to be set as desired.

With regards to plcs12 needing multiple options, we have redhat 8 boxes which come with FIPS enabled.  As the group needs to remain PCI compliant (credit card verification) files must be either AES or 3DES to not get flagged by the scanners. 

So, disabling FIPS is not an option and some apps have limited to no support for AES encoded pkcs12 files.  It's like being between a rock and a hard place.

Thank you for your consideration and time in making this module awesome 👍

**Comment by AGWA** [comment]
Closing in favor of #48

**Pull request closed without merging**
