### PR TITLE
Fix SSL Certificate decode error (pkcs12: expected exactly two items in the authenticated safe) 

### PR DESCRIPTION
**Pull request by fpawel**
The solution for the problem discribed [here](https://github.com/RobotsAndPencils/buford/issues/8). It works well for me.

### CODE REVIEW

**Comment by AGWA** [comment]
As I mentioned in the bug report linked from that bug report, I would review a PR for a `DecodeAll` function: https://github.com/golang/go/issues/14015#issuecomment-458705438

I don't think changing the existing functions to silently ignore extra data is a good idea.

**Comment by AGWA** [comment]
Oh, I just noticed that there's already an open PR for this, #8.  I'll try to take a look soon.

**Comment by fpawel** [comment]
If I understood correctly, this behavior [will not be changed ](https://github.com/SSLMate/go-pkcs12/pull/8/commits/3909fe8238eb5cefc9dd4ce23d04586e42213d0a#diff-0da840cc7e15c66b232f4c7bbfdbe5f1L346)and the problem is not solved

**Comment by AGWA** [comment]
Yes, looking at the PR I agree it is incomplete.

Could you provide an example PKCS#12 which I can use for testing?

**Comment by fpawel** [comment]
@AGWA, I can not unfortunately, because I've got it form AMQP. @tipycalFlow mentioned "Production Apple Push Notification Service", but I have no way to use it. If I create a certificate using OpenSSL, f.e. :
1. `openssl genrsa -out key.pem`
2. `openssl req -new -x509 -extensions v3_ca -keyout key.pem -out cert.pem -days 365`
3. `cat key.pem cert.pem > cert.txt`
4. `openssl pkcs12 -export -in cert.txt -out cert.p12`
then `cert.p12` wil be valid pkcs12 certificate, that your library correctly opens.

**Pull request closed without merging**
